# Prometheus configuration for EthAura monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ethaura-monitor'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Nimbus consensus node metrics
  - job_name: 'nimbus'
    static_configs:
      - targets: ['nimbus:8008']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node exporter (if added)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Frontend nginx metrics (if nginx-prometheus-exporter is added)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']

